name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract version number from tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Substitute placeholders in the manifest
        uses: microsoft/variable-substitution@v1
        with:
          files: "module.json"
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          url: https://github.com/${{github.repository}}
          bugs: https://github.com/${{github.repository}}/issues
          license: https://raw.githubusercontent.com/${{github.repository}}/${{github.event.release.tag_name}}/LICENSE
          readme: https://raw.githubusercontent.com/${{github.repository}}/${{github.event.release.tag_name}}/README.md
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip
      - name: Create module.zip
        run: zip -r ./module.zip module.json README.md LICENSE modules/

      - name: Update Release with Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json, ./module.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
